config/routes.rb
Rails.application.routes.draw do
  resources :toys
  resources :microposts
  resources :users
  root "users#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
end

app/models/toy.rb
class Toy < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  def index
    @microposts = Micropost.all
  end

  def show
  end

  def new
    @micropost = Micropost.new
  end

  def create
    @micropost = Micropost.new(microposts_params)
    if @micropost.save
      redirect_to @micropost
    else
      render "new"
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @micropost = Micropost.find(params[:id])
    @micropost.destroy
    flash[:success] = "The post was successfully removed."
  end
  private
  def microposts_params
    params.require(:micropost).permit(:content, :user_id)
  end
end

app/controllers/toys_controller.rb
class ToysController < ApplicationController
  def index
    @toys = Toy.all
  end

  def show
  end

  def new
    @toy = Toy.new
  end
  def create
    @toy = Toy.new(toy_params)
    if @toy.save
      redirect_to @toy
    else
      render "new"
    end
  end

  def edit
    @toy = Toy.find(params[:id])
  end

  def update
    @toy = Toy.find(params[:id])
    @toy.update(toy_params)
    if @toy.save
      flash[:success] = "This toy was successfully updated."
      redirect_to "/toys"
    else
      render "new"
    end
  end

  def destroy
    @toy = Toy.find(params[:id])
    @toy.destroy
    flash[:success] = "This toy was successfully removed."
  end
  private
  def toy_params
    params.require(:toy).permit(:toy_name, :toy_description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render "new"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      flash[:success] = "This user was successfully updated."
      redirect_to "/users"
    else
      render "new"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "This user was successfully removed."
  end
  private
  def user_params
    params.require(:user).permit(:username, :password, :first_name, :last_name, :email, :phone)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/toys_helper.rb
module ToysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToyApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/microposts/edit.html.erb
<h1>Microposts#edit</h1>
<p>Find me in app/views/microposts/edit.html.erb</p>

app/views/microposts/index.html.erb
<h1>Microposts#index</h1>
<p>Find me in app/views/microposts/index.html.erb</p>
<p id="notice"><%= notice %></p>
<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @microposts.each do |micropost| %>
      <tr>
        <td><%= micropost.content %></td>
        <td><%= micropost.user_id %></td>
        <td><%= link_to 'Show', micropost %></td>
        <td><%= link_to 'Edit', edit_user_path(micropost) %></td>
        <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_micropost_path %>

app/views/microposts/new.html.erb
<h1>Microposts#new</h1>

    <%= form_for (@micropost) do |form| %>
      <%= form.label :content %>
      <%= form.text_field :content, :placeholder => "Write your post here!" %>
      <%= form.label :user_id %>
      <%= form.number_field :user_id, :placeholder => "User ID" %>
      <%= form.submit "Post it!" %>
    <% end %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<h1>Microposts#show</h1>
<p>Find me in app/views/microposts/show.html.erb</p>

app/views/toys/edit.html.erb
<h1>toys#edit</h1>
<p>Find me in app/views/toys/edit.html.erb</p>
    <%= form_for(@toy) do |toy| %>
      <tr>
        <td><%= toy.text_field :toy_name %></td>
        <td><%= toy.text_field :toy_description %></td>
        <td><%= toy.submit %>
      </tr>
    <% end %>

<%= link_to 'Show', @toy %> |
<%= link_to 'Back', toys_path %>

app/views/toys/index.html.erb
<h1>toys#index</h1>
<p>Find me in app/views/toys/index.html.erb</p>
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>Toy</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @toys.each do |toy| %>
      <tr>
        <td><%= toy.toy_name %></td>
        <td><%= toy.toy_description %></td>
        <%# <td><%= link_to 'Show', toy %>
        <%# </td> %>
        <td><%= link_to 'Edit', edit_toy_path(toy) %></td>
        <td><%= link_to 'Destroy', toy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New toy', new_toy_path %>

app/views/toys/new.html.erb
<h1>toys#new</h1>
<p>Find me in app/views/toys/new.html.erb</p>

    <%= form_for (@toy) do |form| %>
      <%= form.label :toy_name %>
      <%= form.text_field :toy_name, :placeholder => "Toy" %>
      <%= form.label :toy_description %>
      <%= form.text_field :toy_description, :placeholder => "Description" %>
      <%= form.submit "Submit" %>
    <% end %>

<%= link_to 'Back', toys_path %>

app/views/toys/show.html.erb
<h1>toys#show</h1>
<p>Find me in app/views/toys/show.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>
Is this it?
   <%= form_for (@user) do |form| %>
      <%= form.label :username %> <br/>
      <%= form.text_field :username %><br/> <br/>
      <%= form.label :first_name %> <br/>
      <%= form.text_field :first_name %><br/> <br/>
      <%= form.label :last_name %> <br/>
      <%= form.text_field :last_name %><br/> <br/>
      <%= form.label :email %> <br/>
      <%= form.email_field :email %><br/> <br/>
      <%= form.label :phone %> <br/>
      <%= form.telephone_field :phone %><br/> <br/>
      <%= form.label :password %> <br/>
      <%= form.password_field :password %> <br/>
      <%= form.submit "Submit" %>
    <% end %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

    <%= form_for (@user) do |form| %>
      <%= form.label :username %>
      <%= form.text_field :username %>
      <%= form.label :first_name %>
      <%= form.text_field :first_name %>
      <%= form.label :last_name %>
      <%= form.text_field :last_name %>
      <%= form.label :email %>
      <%= form.email_field :email %>
      <%= form.label :phone %>
      <%= form.telephone_field :phone %>
      <%= form.label :password %>
      <%= form.password_field :password %>
      <%= form.submit "Submit" %>
    <% end %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>